<?php

abstract class TestCase extends Laravel\Lumen\Testing\TestCase
{
    /**
     * Creates the application.
     *
     * @return \Laravel\Lumen\Application
     */
    protected $us;
    public function createApplication()
    {
        return require __DIR__ . '/../bootstrap/app.php';
    }

        public function actingAs(\Illuminate\Contracts\Auth\Authenticatable $user, $driver = null)
        {
            $this->us = $user;
            return $this;
//            return parent::actingAs($user, $driver); // TODO: Change the autogenerated stub
        }

    public function call($method, $uri, $parameters = [], $cookies = [], $files = [], $server = [], $content = null)
    {
        if ($this->us) {
            $server['HTTP_AUTHORIZATION'] = 'Bearer ' . \Tymon\JWTAuth\Facades\JWTAuth::fromUser($this->us);
        }
        $server['HTTP_ACCEPT'] = 'application/json';
        return parent::call($method, $uri, $parameters, $cookies, $files, $server, $content);
    }



}

